- hosts: localhost
  vars:
  - dbpasswd: localpass
  ## os_family should debian or centos
  - os_family: centos
  - install_dir: /opt/alminium
  - LANG: ja
  - http_proxy: 

  - env: 
      http_proxy: "{{http_proxy}}"
      https_proxy: "{{http_proxy}}"
      INSTALL_DIR: "{{install_dir}}"

#  vars_file:
#  - vars/{{ os_family }}.yml

  roles:
#  - mariadb
#  - redmine
#  - vcs
  - redmine-plugins
