- hosts: localhost
  vars:
  - dbpasswd: localpass
  - LANG: ja
  - http_proxy: 
  - env: 
      http_proxy: "{{http_proxy}}"
      https_proxy: "{{http_proxy}}"
      INSTALL_DIR: /opt/alminium

  roles:
  - mariadb
  - redmine
  - vcs
  - redmine-plugins


  tasks:
  - include: tasks/packages.yml
  - include: tasks/initdb.yml
  - include: tasks/install-redmine.yml
  - include: tasks/install-plugins.yml
  - script: scripts/init-redmine-plugins.sh
    environment: env
  - copy: src=files/init.mysql dest=/tmp
  - command: mysql alminium -e "source /tmp/init.mysql"

