- hosts: localhost
  vars:
  - dbpasswd: localpass
  ## os_family should debian or centos
  - os_family: centos
  - install_dir: /opt/alminium
  - LANG: ja
  - proxy_host: 
  - proxy_port: 
  - http_proxy: http://{{proxy_host}}:{{proxy_port}}/
    when: proxy_host is defined
#  - http_proxy: 
#    when: proxy_host is undefined
  - env: 
      http_proxy: "{{http_proxy}}"
      https_proxy: "{{http_proxy}}"
      INSTALL_DIR: "{{install_dir}}"

  vars_files:
  - vars/{{ os_family }}.yml


  roles:
  - proxyconfig
  - mariadb
  - redmine
  - vcs
  - redmine-plugins
