- name: Create Database
  mysql_db: name=alminium encoding=utf8 state=present

- name: Create User on MySQL/MariaDB
  mysql_user: name=alminium password="{{dbpasswd}}" priv=alminium.*:ALL state=present


