- debug: msg="============= Setup Redmine ====================="

- name: Checkout Redmine Source Code
  git: repo=https://github.com/redmine/redmine.git version=2.5.2 dest=/opt/alminium depth=1
#  subversion: repo=http://svn.redmine.org/redmine/tags/2.5.2 dest=/opt/alminium
  environment:
    https_proxy: "{{http_proxy}}"

- name: Create Redmine Database Configuration
  template: src=templates/database.yml.j2 dest=/opt/alminium/config/database.yml owner=apache group=apache


- script: scripts/install-redmine.sh /opt/alminium
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{http_proxy}}"

- name: Create Apache Configuration
  template: src=templates/redmine.conf.j2 dest=/etc/httpd/conf.d/redmine.conf owner=apache group=apache

- name: Create Git/Subversion/Mercurial Apache Configuration
  template: src=templates/vcs.conf.j2 dest=/etc/httpd/conf.d/vcs.conf owner=apache group=apache

- file: path=/etc/httpd/Apache/Authn state=directory owner=apache group=apache
- copy: src=resources/Redmine.pm dest=/etc/httpd/Apache/Authn

