- copy: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo

- yum: name={{ item }} state=installed
  with_items:
  - MariaDB
  - MariaDB-devel
  - MySQL-python

- service: name=mysql state=started

- name: Create Database
  mysql_db: name={{dbname}} encoding=utf8 state=present

- name: Create User on MySQL/MariaDB
  mysql_user: name={{dbuser}} host='*' password="{{dbpasswd}}" priv={{dbname}}.*:ALL state=present


